services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: exchange
      POSTGRES_PASSWORD: exchange
      POSTGRES_DB: exchange
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U exchange" ]
      start_interval: 1s
      start_period: 10s
      interval: 5m

volumes:
  postgres-data:
