apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- range $path, $deployment := .Values.ingress.routes }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-{{ $deployment }}
                port:
                  name: http
          {{- end }}
    {{- if .Values.redpanda.console.enabled }}
    - host: {{ .Values.ingress.consoleHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-console
                port:
                  number: 8080
    {{- end }}
